Feature/hello world
kensayo/hello-rails-react pull request #1
Opened 2021-12-15 03:12 UTC by kensayo

2021-12-15 05:13 UTC, Davidosky007 commented
Hi @kensayo 👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no pull request description 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2021-12-15 12:35 UTC, AshakaE requested changes
### Hi @kensayo  🙋‍♀️, 

Good job so far! 👌

Your:
   - Project is impressive 👏 
   - Git flow ✔️ 
   - Pull request 👍 
   - README 👌 
   
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._

###  Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 12:35 UTC, AshakaE commented on db/seeds.rb
> +# rubocop:enable Lint/Syntax
- [ ] Kindly fix the syntax error in your db seed 😄

2021-12-15 12:35 UTC, AshakaE commented on config/routes.rb
> +  root 'statics#index'
- [ ] Kindly fix the root page view , I'm getting this error
![image](https://user-images.githubusercontent.com/67957533/146187174-fd010901-b806-4a6d-84b3-88f8be939d36.png)

2021-12-15 12:35 UTC, AshakaE commented on README.md
> +- Then just go to [http://127.0.0.1:3000/](http://127.0.0.1:3000/)
- [ ] Kindly update this link to take the user to the right greetings page

2021-12-16 23:08 UTC, enaburekhan approved these changes
Hi Kensayo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 23:56 UTC, merged